name: Test

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: macos
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v14
    - name: Build
      run: nix-build -A mpvc